cache:
  paths:
   - node_modules/

before_script:
  - npm install
  
pages:
  stage: deploy
  
  script:
    - gulp build
    - cd dist
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master